import random
import re
from datetime import datetime

QUOTES = [
    ('💡', '"A qualidade nunca é um acidente; é sempre o resultado de um esforço inteligente."', 'John Ruskin'),
    ('🚀', '"Automatize o repetível para liberar tempo para o que importa."', 'Fernando Wegner'),
    ('🔍', '"Testar é questionar o software com inteligência, não apenas executar casos."', 'James Bach'),
    ('⚡', '"A melhor performance é aquela que o usuário nunca percebe que existiu."', 'Anônimo'),
    ('🛡️', '"Segurança não é um produto, é um processo contínuo."', 'Bruce Schneier'),
    ('🤖', '"CI/CD não acelera o deploy — acelera o aprendizado."', 'Jez Humble'),
    ('📊', '"Sem métricas, qualidade é apenas uma opinião."', 'Tom DeMarco'),
    ('🌐', '"A cloud não é o destino, é o meio para entregar valor mais rápido."', 'Werner Vogels'),
    ('🧪', '"Um bug encontrado em produção custa 100x mais do que encontrado em teste."', 'Barry Boehm'),
    ('🎯', '"Qualidade é responsabilidade de todos, mas começa com quem testa."', 'Anônimo'),
    ('💻', '"O código limpo faz uma coisa bem feita."', 'Robert C. Martin'),
    ('🔧', '"DevOps é cultura primeiro, ferramentas depois."', 'Patrick Debois'),
    ('📈', '"Monitore tudo. Você não pode melhorar o que não mede."', 'Peter Drucker'),
    ('🏆', '"Excelência não é uma habilidade, é uma atitude."', 'Ralph Marston'),
    ('🌱', '"Todo sistema legado já foi moderno algum dia. Respeite-o enquanto o evolui."', 'Anônimo'),
    ('🔑', '"Simplicidade é o requisito final da arte."', 'Leonardo da Vinci'),
    ('🧠', '"Qualquer tolo pode escrever código que um computador entende. Bons programadores escrevem código que humanos entendem."', 'Martin Fowler'),
    ('🌟', '"Primeiro faça funcionar, depois faça rápido, depois faça bonito."', 'Kent Beck'),
    ('🔐', '"A segurança que não foi testada não é segurança, é esperança."', 'Anônimo'),
    ('📦', '"Containers não resolvem problemas de arquitetura — apenas os tornam mais portáteis."', 'Anônimo'),
    ('🎲', '"Todo sistema tem bugs. O diferencial é quão rápido você os encontra e corrige."', 'Anônimo'),
    ('🔗', '"APIs são contratos. Quebre-os e quebrará a confiança."', 'Anônimo'),
    ('🌊', '"Agile não é velocidade, é capacidade de responder à mudança."', 'Martin Fowler'),
    ('🏗️', '"Arquitetura boa é aquela que adiará as decisões difíceis o máximo possível."', 'Robert C. Martin'),
    ('💾', '"Dados são o novo petróleo, mas bruto também não vale nada."', 'Clive Humby'),
    ('🎮', '"O melhor código é o que não precisa ser escrito."', 'Jeff Atwood'),
    ('🔭', '"Inovação é ver o que todo mundo vê e pensar o que ninguém pensou."', 'Albert Szent-Györgyi'),
    ('🌍', '"Software está comendo o mundo."', 'Marc Andreessen'),
    ('⚙️', '"Automatize tudo que pode falhar por erro humano."', 'Anônimo'),
    ('🧩', '"Microserviços resolvem problemas de escala que a maioria das empresas nunca terá."', 'Anônimo'),
    ('📱', '"Mobile first não é tendência, é realidade."', 'Anônimo'),
    ('🔄', '"Refatorar sem testes é como limpar a casa com os olhos fechados."', 'Anônimo'),
    ('🎯', '"Um teste que nunca falhou nunca foi útil."', 'Anônimo'),
    ('💎', '"Código é lido 10x mais do que escrito. Escreva para quem vai ler."', 'Anônimo'),
    ('🚧', '"Débito técnico é como dívida financeira: juros compõem."', 'Ward Cunningham'),
    ('🌈', '"Diversidade de perspectivas cria software melhor."', 'Anônimo'),
    ('🔬', '"TDD não é sobre testes, é sobre design."', 'Kent Beck'),
    ('📡', '"Monitoramento sem alerta é como câmera de segurança sem ninguém assistindo."', 'Anônimo'),
    ('🎵', '"Bom código tem ritmo. Você sente quando está certo."', 'Anônimo'),
    ('🏄', '"Surfe na onda da mudança ou seja engolido por ela."', 'Anônimo'),
    ('🔩', '"Infraestrutura como código é a única infraestrutura que você pode fazer revisão."', 'Anônimo'),
    ('🌙', '"Deploy na sexta à tarde é um ato de fé, não de engenharia."', 'Anônimo'),
    ('🎬', '"O rollback mais rápido é aquele que você planejou antes do deploy."', 'Anônimo'),
    ('🏋️', '"Performance não é feature, é fundação."', 'Anônimo'),
    ('🌺', '"UX ruim é um bug de produto, não de código."', 'Anônimo'),
    ('🔮', '"Predizer falhas é mais valioso do que reagir a elas."', 'Anônimo'),
    ('🎓', '"Todo sênior já foi júnior que não desistiu."', 'Anônimo'),
    ('🦅', '"Voe alto nos requisitos, rasteje nos detalhes de implementação."', 'Anônimo'),
    ('🌵', '"Resiliência é sobre falhar graciosamente, não sobre não falhar."', 'Anônimo'),
    ('🎪', '"Stand-up não é reunião de status, é sincronização de equipe."', 'Anônimo'),
    ('🔥', '"Hotfix em produção: quando o plano A falhou e o plano B virou o plano A."', 'Anônimo'),
    ('🏰', '"Sistemas distribuídos são sistemas que falham de formas que você ainda não imaginou."', 'Leslie Lamport'),
    ('🌠', '"O futuro pertence a quem automatiza o presente."', 'Anônimo'),
    ('🎯', '"Cada sprint é uma oportunidade de entregar valor, não apenas tarefas."', 'Anônimo'),
    ('🦾', '"IA não substituirá programadores. Programadores que usam IA substituirão os que não usam."', 'Anônimo'),
    ('🧬', '"Evolua o sistema em pequenos passos. Revoluções em produção são perigosas."', 'Anônimo'),
    ('🌊', '"Logs são a memória do sistema. Sem eles, você é cego no passado."', 'Anônimo'),
    ('🎸', '"Clean code não é sobre estética, é sobre manutenibilidade."', 'Anônimo'),
    ('🔴', '"Todo sistema tem um ponto de falha. Encontre-o antes que o usuário encontre."', 'Anônimo'),
    ('🏁', '"Definição de pronto sem testes automatizados não é definição de pronto."', 'Anônimo'),
    ('🌻', '"Cultura DevOps começa quando Dev e Ops param de se culpar."', 'Anônimo'),
    ('🎠', '"Kubernetes resolve problemas de orquestração e cria problemas de complexidade."', 'Anônimo'),
    ('🦁', '"Coragem em engenharia é questionar requisitos impossíveis."', 'Anônimo'),
    ('🌴', '"Documentação desatualizada é pior do que nenhuma documentação."', 'Anônimo'),
    ('🔵', '"Blue-green deployment: a arte de enganar o usuário enquanto você troca o motor do avião em voo."', 'Anônimo'),
    ('🧲', '"Boas APIs atraem bons integradores."', 'Anônimo'),
    ('🎋', '"Bamboo cresce devagar mas é mais forte que o carvalho. Código robusto leva tempo."', 'Anônimo'),
    ('🏔️', '"Escalabilidade não é sobre suportar picos, é sobre sobreviver a eles com elegância."', 'Anônimo'),
    ('🌊', '"Chaos engineering: quebre seu sistema antes que ele quebre você."', 'Netflix'),
    ('🎯', '"Requisito ambíguo é bug ainda não escrito."', 'Anônimo'),
    ('🔑', '"Acesso mínimo privilegiado: dê apenas o que precisa, quando precisa."', 'Anônimo'),
    ('🌟', '"O melhor sistema de backup é o que você nunca precisou usar, mas sabe que funciona."', 'Anônimo'),
    ('🚀', '"Velocity não é sobre ir rápido, é sobre ir na direção certa."', 'Anônimo'),
    ('🧊', '"Freeze de código não para bugs. Para apenas a descoberta deles."', 'Anônimo'),
    ('🎭', '"Ambientes de homologação que não espelham produção são teatro."', 'Anônimo'),
    ('🌈', '"Diversidade de tecnologia sem padronização é caos colorido."', 'Anônimo'),
    ('🏊', '"Nadar contra a corrente da legacy é possível, mas exaustivo. Mude o rio."', 'Anônimo'),
    ('🔧', '"Ferramenta certa para o trabalho certo. Martelo não é chave de fenda."', 'Anônimo'),
    ('🌺', '"Sprint review sem stakeholders é conversa interna sem impacto."', 'Anônimo'),
    ('🎲', '"Teste de carga revela a verdade que o teste funcional esconde."', 'Anônimo'),
    ('💡', '"Insight vem de dados. Sabedoria vem de entender os dados."', 'Anônimo'),
    ('🔭', '"Observability é sobre fazer perguntas ao sistema que você ainda não sabe que terá."', 'Charity Majors'),
    ('🏆', '"Code review não é auditoria, é colaboração."', 'Anônimo'),
    ('🌱', '"Cada commit é uma história. Escreva mensagens que a contem."', 'Anônimo'),
    ('🧪', '"Testes de contrato salvam microsserviços de si mesmos."', 'Anônimo'),
    ('⚡', '"Latência percebida pelo usuário é a única métrica que importa no frontend."', 'Anônimo'),
    ('🎪', '"Retrospectiva sem ação é terapia de grupo."', 'Anônimo'),
    ('🦋', '"Refatoração é metamorfose controlada do código."', 'Anônimo'),
    ('🌍', '"Open source não é gratuito, é uma troca de valor diferente."', 'Anônimo'),
    ('🔐', '"Zero trust: confie em ninguém, verifique todos."', 'John Kindervag'),
    ('🎯', '"OKRs sem métricas são desejos."', 'Anônimo'),
    ('🏗️', '"MVP não é produto ruim entregue rápido. É a hipótese mínima para validar valor."', 'Eric Ries'),
    ('💻', '"O teclado é o instrumento. O código é a música."', 'Anônimo'),
    ('🌙', '"Alertas que ninguém responde são ruído. Ruído mata a cultura de on-call."', 'Anônimo'),
    ('🎵', '"Pipelines CI quebradas são semáforos vermelhos que todos ignoram."', 'Anônimo'),
    ('🔬', '"Análise de causa raiz: não pare no primeiro culpado, vá fundo."', 'Anônimo'),
    ('🌊', '"Feature flag é o freio de mão do deploy contínuo."', 'Anônimo'),
    ('🏋️', '"Performance testing é academia para o sistema. Teste antes do jogo."', 'Anônimo'),
    ('🎬', '"Documentação de API é a interface humana do seu serviço."', 'Anônimo'),
    ('🌵', '"Sistemas autônomos falham autonomamente. Projete o fail-safe primeiro."', 'Anônimo'),
    ('🔮', '"Machine learning sem dados de qualidade é alquimia moderna."', 'Anônimo'),
    ('🦅', '"Visão de produto sem execução técnica é sonho. Execução sem visão é pesadelo."', 'Anônimo'),
    ('🎓', '"Mentorar é multiplicar impacto além do seu próprio código."', 'Anônimo'),
    ('🌠', '"Automação libera humanos para problemas que máquinas ainda não resolvem."', 'Anônimo'),
    ('🧬', '"Arquitetura evolutiva: projete para mudar, não para durar."', 'Neal Ford'),
    ('🎸', '"Pair programming: dois cérebros, um teclado, metade dos bugs."', 'Anônimo'),
    ('🏰', '"Monolito bem feito é melhor que microsserviço mal feito."', 'Anônimo'),
    ('🌻', '"Shift left em segurança: quanto mais cedo, mais barato corrigir."', 'Anônimo'),
    ('🔴', '"Incident post-mortem sem blameless é punição disfarçada de processo."', 'Anônimo'),
    ('🎠', '"SLA é promessa. SLO é meta. SLI é realidade."', 'Google SRE'),
    ('🌴', '"Código comentado é código morto. Delete-o."', 'Robert C. Martin'),
    ('🧲', '"Boa UX faz o usuário sentir que o sistema leu sua mente."', 'Anônimo'),
    ('🏔️', '"Escalar horizontalmente é democracia. Escalar verticalmente é aristocracia."', 'Anônimo'),
    ('🎋', '"Paciência com legacy, impaciência com stagnação."', 'Anônimo'),
    ('🦾', '"Automação de testes não é luxo, é seguro de vida do software."', 'Anônimo'),
    ('🌈', '"GraphQL: pergunte exatamente o que precisa, receba exatamente isso."', 'Anônimo'),
    ('🏊', '"Debugging é como detetive: elimine o impossível, aceite o improvável."', 'Sherlock Holmes adaptado'),
    ('🔵', '"Branching strategy ruim é fonte de conflitos — no Git e na equipe."', 'Anônimo'),
    ('💾', '"ETL mal feito é dado ruim com boa aparência."', 'Anônimo'),
    ('🎲', '"A/B testing: deixe os dados escolherem, não a hierarquia."', 'Anônimo'),
    ('🌊', '"Event-driven architecture: reaja ao passado para preparar o futuro."', 'Anônimo'),
    ('🔩', '"Infraestrutura imutável: não conserte servidores, substitua-os."', 'Anônimo'),
    ('🌺', '"Feedback rápido é oxigênio para o desenvolvimento ágil."', 'Anônimo'),
    ('🎭', '"Persona de usuário sem pesquisa real é ficção científica de produto."', 'Anônimo'),
    ('🧊', '"Cache é a resposta para tudo, exceto para consistência."', 'Anônimo'),
    ('🎯', '"Qualidade de código é responsabilidade do time, não do QA."', 'Anônimo'),
    ('🦁', '"Liderança técnica é sobre elevar o time, não sobre ser o melhor programador."', 'Anônimo'),
    ('🔑', '"Criptografia forte com chave fraca é porta blindada com janela aberta."', 'Anônimo'),
    ('🚀', '"Platform engineering: construa estradas para que outros construam cidades."', 'Anônimo'),
    ('🌟', '"Observabilidade sem ação é voyeurismo de sistema."', 'Anônimo'),
    ('🧠', '"Complexidade acidental é o inimigo. Combata-a diariamente."', 'Fred Brooks'),
    ('🎪', '"Daily sem bloqueios visíveis não significa ausência de bloqueios."', 'Anônimo'),
    ('🌍', '"API-first design: pense no contrato antes do código."', 'Anônimo'),
    ('🏆', '"Continuous delivery é sobre confiança: no código, no processo e na equipe."', 'Anônimo'),
    ('💡', '"O melhor algoritmo é o que resolve o problema com os recursos disponíveis."', 'Anônimo'),
    ('🔭', '"Telemetria é o sistema nervoso do software moderno."', 'Anônimo'),
    ('🌱', '"Onboarding técnico ruim é o primeiro passo para o churn de talentos."', 'Anônimo'),
    ('⚡', '"Otimização prematura é a raiz de todo mal."', 'Donald Knuth'),
    ('🎵', '"Código bom envelhece bem. Código ruim envelhece mal e fica."', 'Anônimo'),
    ('🦋', '"Cada deploy bem-sucedido é um voto de confiança no processo."', 'Anônimo'),
    ('🌊', '"Eventual consistency: a verdade chega, só não sei quando."', 'Anônimo'),
    ('🔬', '"Static analysis é o revisor que nunca dorme e nunca tem ego."', 'Anônimo'),
    ('🏗️', '"Domain-driven design: fale a língua do negócio no código."', 'Eric Evans'),
    ('🎬', '"Versionamento semântico é comunicação. MAJOR.MINOR.PATCH conta uma história."', 'Anônimo'),
    ('🌵', '"Downtime planejado é manutenção. Downtime não planejado é aprendizado caro."', 'Anônimo'),
    ('🔮', '"Predição sem dados históricos é adivinhação com vocabulário técnico."', 'Anônimo'),
    ('🧬', '"DevSecOps: segurança não é portão final, é ingrediente de cada etapa."', 'Anônimo'),
    ('🎸', '"Boa documentação é o presente que você dá para você mesmo no futuro."', 'Anônimo'),
    ('🏰', '"Fault tolerance é sobre sobreviver à falha, não sobre evitá-la."', 'Anônimo'),
    ('🌻', '"Kanban: visualize o fluxo, limite o trabalho em progresso, melhore continuamente."', 'Taiichi Ohno'),
    ('🔴', '"Bug em produção tem nome e sobrenome: falta de teste."', 'Anônimo'),
    ('🎠', '"GitOps: se não está no repositório, não existe."', 'Anônimo'),
    ('🌴', '"Segurança by design, não by afterthought."', 'Anônimo'),
    ('🧲', '"Developer experience ruim é talent retention ruim."', 'Anônimo'),
    ('🏔️', '"Alta disponibilidade é compromisso de arquitetura, não de sorte."', 'Anônimo'),
    ('🎋', '"Tecnologia muda. Princípios de bom design permanecem."', 'Anônimo'),
    ('🦾', '"IaC é o único jeito de ter infraestrutura auditável."', 'Anônimo'),
    ('🌈', '"Testes de regressão são a memória coletiva do software."', 'Anônimo'),
    ('🏊', '"Swim lanes no Kanban: visualize gargalos antes que virem crises."', 'Anônimo'),
    ('🔵', '"Chaos monkey: o melhor QA é o que ataca a produção de forma controlada."', 'Netflix'),
    ('💾', '"Data lake sem governança é pântano de dados."', 'Anônimo'),
    ('🎲', '"Testes exploratórios encontram o que testes roteirizados nunca imaginariam."', 'Anônimo'),
    ('🌊', '"Service mesh: gerencie a comunicação entre serviços, não dentro deles."', 'Anônimo'),
    ('🔩', '"Idempotência: execute quantas vezes quiser, o resultado é sempre o mesmo."', 'Anônimo'),
    ('🌺', '"Product backlog sem priorização é lista de desejos sem orçamento."', 'Anônimo'),
    ('🎭', '"Shadow testing: teste em produção sem afetar produção."', 'Anônimo'),
    ('🧊', '"Timeout é a resposta honesta quando você não sabe quando vai terminar."', 'Anônimo'),
    ('🎯', '"Acceptance criteria é o contrato entre produto e engenharia."', 'Anônimo'),
    ('🦁', '"Sênior não é quem sabe tudo, é quem sabe onde procurar e quando perguntar."', 'Anônimo'),
    ('🔑', '"Gestão de secrets: nunca no código, sempre no vault."', 'Anônimo'),
    ('🚀', '"Trunk-based development: integre cedo, integre sempre, evite merges dolorosos."', 'Anônimo'),
    ('🌟', '"Engenharia de confiabilidade é sobre errar com elegância."', 'Anônimo'),
    ('🧠', '"Sistemas complexos falham de formas complexas. Simplifique onde puder."', 'Anônimo'),
    ('🎪', '"Retrospectiva eficaz gera ação, não apenas conversa."', 'Anônimo'),
    ('🌍', '"REST não é só GET e POST. É sobre recursos, estado e hipermídia."', 'Roy Fielding'),
    ('🏆', '"O código mais seguro é o que nunca foi escrito."', 'Anônimo'),
    ('💡', '"Integração contínua sem build rápido é integração descontinuada na prática."', 'Anônimo'),
    ('🔭', '"APM é o termômetro do sistema em produção."', 'Anônimo'),
    ('🌱', '"Todo grande sistema começou como um pequeno script."', 'Anônimo'),
    ('⚡', '"Caching resolve latência. Invalidação de cache resolve complexidade."', 'Anônimo'),
    ('🎵', '"Bons testes são especificações executáveis."', 'Anônimo'),
    ('🦋', '"Código que não pode ser testado é código que não confia em si mesmo."', 'Anônimo'),
    ('🌊', '"Eventual consistency + idempotência = sistema distribuído resiliente."', 'Anônimo'),
    ('🔬', '"Profiling revela verdades que o code review nunca vê."', 'Anônimo'),
    ('🏗️', '"CQRS: separe leitura de escrita e escale cada uma no seu ritmo."', 'Anônimo'),
    ('🎬', '"Feature creep é o câncer silencioso do produto."', 'Anônimo'),
    ('🌵', '"On-call sem runbook é bombeiro sem mangueira."', 'Anônimo'),
    ('🔮', '"LLMs não pensam, reconhecem padrões em escala absurda."', 'Anônimo'),
    ('🧬', '"Shift left testing: mova os testes para onde os problemas são criados."', 'Anônimo'),
    ('🎸', '"Pull request pequeno é pull request revisado."', 'Anônimo'),
    ('🏰', '"Bulkhead pattern: isole falhas como compartimentos de um navio."', 'Anônimo'),
    ('🌻', '"SRE é o que acontece quando você pede para um engenheiro de software operar sistemas."', 'Google'),
    ('🔴', '"Alerta de falso positivo mata a atenção. Calibre seus alertas."', 'Anônimo'),
    ('🎠', '"Pipeline como código: sua infraestrutura de entrega também merece versionamento."', 'Anônimo'),
    ('🌴', '"Dependency injection: não construa suas dependências, receba-as."', 'Anônimo'),
    ('🧲', '"Stakeholder satisfeito é aquele que recebe o que pediu e entende por que não é o que precisa."', 'Anônimo'),
    ('🏔️', '"Resiliência de sistema começa na resiliência da equipe."', 'Anônimo'),
    ('🎋', '"Cada linha de código adicionada é responsabilidade futura de manutenção."', 'Anônimo'),
    ('🦾', '"Serverless não é sem servidor, é servidor que você não gerencia."', 'Anônimo'),
    ('🌈', '"Test pyramid: muitos unitários, menos integração, poucos E2E."', 'Mike Cohn'),
    ('🏊', '"Swim or sink: software que não evolui afunda."', 'Anônimo'),
    ('🔵', '"Blue ocean de tecnologia: resolva problemas que a concorrência ainda não viu."', 'Anônimo'),
    ('💾', '"Schema migration sem rollback plan é aposta em produção."', 'Anônimo'),
    ('🎲', '"Fuzzing: deixe o caos revelar as falhas que sua imaginação não alcança."', 'Anônimo'),
    ('🌊', '"WebSockets para real-time. Polling para preguiçosos."', 'Anônimo'),
    ('🔩', '"Princípio da responsabilidade única: uma razão para mudar."', 'Robert C. Martin'),
    ('🌺', '"Épico sem critérios de aceite é viagem sem destino."', 'Anônimo'),
    ('🎭', '"Canary release: deixe 1% dos usuários descobrir o bug antes de todos."', 'Anônimo'),
    ('🧊', '"Rate limiting: proteja seus serviços dos seus próprios usuários."', 'Anônimo'),
    ('🎯', '"KPI sem baseline é número sem contexto."', 'Anônimo'),
    ('🦁', '"Código legado é herança. Trate com respeito, mas não deixe paralisar."', 'Anônimo'),
    ('🔑', '"OAuth2 + PKCE: autenticação mobile do jeito certo."', 'Anônimo'),
    ('🚀', '"Progressive delivery: entregue para poucos, aprenda, expanda."', 'Anônimo'),
    ('🌟', '"Engineering excellence não é perfeição, é melhoria contínua."', 'Anônimo'),
    ('🧠', '"Problema bem definido é problema meio resolvido."', 'Charles Kettering'),
    ('🎪', '"Cerimônias ágeis sem propósito claro são burocracia com post-its."', 'Anônimo'),
    ('🌍', '"Open API specification: sua API fala por si mesma."', 'Anônimo'),
    ('🏆', '"A arte do bom QA é encontrar bugs que o dev nunca imaginou escrever."', 'Anônimo'),
    ('💡', '"Logs estruturados são dados. Logs de texto são ruído."', 'Anônimo'),
    ('🔭', '"Distributed tracing: siga a requisição por todos os serviços até a verdade."', 'Anônimo'),
    ('🌱', '"Junior que faz perguntas cresce. Junior que finge entender estagna."', 'Anônimo'),
    ('⚡', '"React fast to failures. Learn faster from them."', 'Anônimo'),
    ('🎵', '"Código limpo não precisa de comentário. Código confuso não merece comentário."', 'Anônimo'),
    ('🦋', '"Cada refatoração bem feita é uma dívida técnica paga."', 'Anônimo'),
    ('🌊', '"Event sourcing: o estado atual é a soma de todos os eventos passados."', 'Anônimo'),
    ('🔬', '"Security scanning no pipeline: encontre vulnerabilidades antes do atacante."', 'Anônimo'),
    ('🏗️', '"Twelve-factor app: manifesto para software moderno e portátil."', 'Heroku'),
    ('🎬', '"Dark launch: a feature existe, os usuários não sabem ainda."', 'Anônimo'),
    ('🌵', '"Postmortem blameless: foque no sistema, não no humano."', 'Anônimo'),
    ('🔮', '"Vector database: busca semântica é a nova busca por keyword."', 'Anônimo'),
    ('🧬', '"Continuous improvement: nunca está perfeito, sempre pode melhorar 1%."', 'Anônimo'),
    ('🎸', '"Dead code é peso morto. Delete com confiança se tem testes."', 'Anônimo'),
    ('🏰', '"Circuit breaker: pare de tentar quando o sistema downstream está morto."', 'Michael Nygard'),
    ('🌻', '"Platform team: enablement primeiro, governance depois."', 'Anônimo'),
    ('🔴', '"P0 em produção: comunicação clara > solução perfeita."', 'Anônimo'),
    ('🎠', '"ArgoCD + GitOps: o cluster aplica o que o Git manda."', 'Anônimo'),
    ('🌴', '"SOLID: os cinco princípios que separam código de legado de código de qualidade."', 'Robert C. Martin'),
    ('🧲', '"Documentação como código: versione, revise, mantenha atualizada."', 'Anônimo'),
    ('🏔️', '"Horizontal scaling funciona para stateless. Stateful é mais complicado."', 'Anônimo'),
    ('🎋', '"Código que funciona mas ninguém entende é bomba-relógio."', 'Anônimo'),
    ('🦾', '"MLOps: aplique DevOps para modelos de machine learning."', 'Anônimo'),
    ('🌈', '"BDD: escreva cenários que o negócio entenda e o código execute."', 'Dan North'),
    ('🏊', '"Nadar com dados: use analytics para decisões, não intuição."', 'Anônimo'),
    ('🔵', '"Blue team vs red team: ataque simulado, defesa real."', 'Anônimo'),
    ('💾', '"Backup testado é backup. Backup não testado é esperança."', 'Anônimo'),
    ('🎲', '"Mutation testing: teste seus testes matando seu código."', 'Anônimo'),
    ('🌊', '"Saga pattern: transações distribuídas sem locks distribuídos."', 'Anônimo'),
    ('🔩', '"Interface segregation: não force implementações desnecessárias."', 'Robert C. Martin'),
    ('🌺', '"Story map: visualize a jornada antes de fatiar em sprints."', 'Jeff Patton'),
    ('🎭', '"Feature toggle: ligue e desligue funcionalidades sem deploy."', 'Anônimo'),
    ('🧊', '"Graceful degradation: quando partes falham, o todo ainda funciona."', 'Anônimo'),
    ('🎯', '"Definition of Done é o contrato de qualidade do time."', 'Anônimo'),
    ('🦁', '"Tech lead que não codifica perde o contexto. Perde o contexto, perde a liderança."', 'Anônimo'),
    ('🔑', '"JWT sem expiração é chave sem fechadura."', 'Anônimo'),
    ('🚀', '"Deploy contínuo é confiança automatizada."', 'Anônimo'),
    ('🌟', '"Engenharia é sobre trade-offs, não sobre soluções perfeitas."', 'Anônimo'),
    ('🧠', '"Conway\'s Law: sistemas espelham a estrutura de comunicação das organizações."', 'Melvin Conway'),
    ('🎪', '"Velocity de time não é produtividade individual somada."', 'Anônimo'),
    ('🌍', '"SDK bem documentado é produto. SDK mal documentado é obstáculo."', 'Anônimo'),
    ('🏆', '"O melhor teste de segurança é o que o atacante nunca esperava que você fizesse."', 'Anônimo'),
    ('💡', '"Métricas de negócio > métricas de engenharia. Alinhe os dois."', 'Anônimo'),
    ('🔭', '"End-to-end observability: veja a jornada completa do usuário no sistema."', 'Anônimo'),
    ('🌱', '"Cultura de aprendizado: erro é dado, não punição."', 'Anônimo'),
    ('⚡', '"TTFB baixo: a primeira impressão do seu servidor."', 'Anônimo'),
    ('🎵', '"Design patterns são vocabulário, não receita."', 'Anônimo'),
    ('🦋', '"Strangler fig pattern: modernize o legado sem reescrever tudo de uma vez."', 'Martin Fowler'),
    ('🌊', '"CRDT: dados que convergem mesmo sem coordenação central."', 'Anônimo'),
    ('🔬', '"DAST vs SAST: teste dinâmico e estático são complementares, não excludentes."', 'Anônimo'),
    ('🏗️', '"Hexagonal architecture: isole o domínio do mundo externo."', 'Alistair Cockburn'),
    ('🎬', '"Release notes são o changelog que o usuário lê."', 'Anônimo'),
    ('🌵', '"Runbook automatizado é o próximo passo do runbook manual."', 'Anônimo'),
    ('🔮', '"Prompt engineering é a nova arte de fazer a máquina entender você."', 'Anônimo'),
    ('🧬', '"Inner source: aplique práticas open source dentro da empresa."', 'Anônimo'),
    ('🎸', '"Mob programming: o time inteiro em um problema ao mesmo tempo."', 'Anônimo'),
    ('🏰', '"Retry com exponential backoff: persista sem afogar o sistema downstream."', 'Anônimo'),
    ('🌻', '"Developer portal: o shopping center das plataformas internas."', 'Anônimo'),
    ('🔴', '"Severity vs priority: urgência não é sempre importância."', 'Anônimo'),
    ('🎠', '"Helm charts: empacote sua aplicação Kubernetes."', 'Anônimo'),
    ('🌴', '"Liskov substitution: subtipos devem ser substituíveis por seus tipos base."', 'Barbara Liskov'),
    ('🧲', '"Inner feedback loop rápido = desenvolvedor feliz e produtivo."', 'Anônimo'),
    ('🏔️', '"Multi-region deployment: latência baixa globalmente ou disponibilidade global?"', 'Anônimo'),
    ('🎋', '"Comentário que explica O QUÊ o código faz é redundante. Explique O PORQUÊ."', 'Anônimo'),
    ('🦾', '"AutoML não elimina o cientista de dados. Elimina o trabalho chato."', 'Anônimo'),
    ('🌈', '"Contract testing: integração sem dependência de ambiente compartilhado."', 'Anônimo'),
    ('🏊', '"Technical excellence sem entrega de valor é masturbação intelectual."', 'Anônimo'),
    ('🔵', '"Penetration testing: encontre as brechas antes que o atacante as encontre."', 'Anônimo'),
    ('💾', '"Data mesh: trate dados como produto, com dono e qualidade garantida."', 'Zhamak Dehghani'),
    ('🎲', '"Property-based testing: gere milhares de casos que você nunca escreveria manualmente."', 'Anônimo'),
    ('🌊', '"Reactive systems: responsivos, resilientes, elásticos e orientados a mensagem."', 'Reactive Manifesto'),
    ('🔩', '"Open/Closed principle: aberto para extensão, fechado para modificação."', 'Bertrand Meyer'),
    ('🌺', '"User story mapping revela gaps que o backlog plano esconde."', 'Anônimo'),
    ('🎭', '"A/B test sem significância estatística é coinflip com dashboard."', 'Anônimo'),
    ('🧊', '"Dead letter queue: os erros que você não pode ignorar, mas não pode processar agora."', 'Anônimo'),
    ('🎯', '"Threshold de cobertura de testes: piso, não teto."', 'Anônimo'),
    ('🦁', '"Liderança por contexto, não por controle."', 'Netflix Culture'),
    ('🔑', '"mTLS: ambos os lados provam quem são."', 'Anônimo'),
    ('🚀', '"Internal developer platform: a alavanca de produtividade da engenharia."', 'Anônimo'),
    ('🌟', '"Qualidade não é departamento, é mentalidade."', 'Anônimo'),
    ('🧠', '"Feedback loop rápido é o coração do desenvolvimento ágil."', 'Anônimo'),
    ('🎪', '"PI Planning: alinhe trens ágeis antes de soltar na trilha."', 'SAFe'),
    ('🌍', '"Semantic versioning é comunicação de impacto de mudança."', 'Anônimo'),
    ('🏆', '"Automação de testes é investimento. Teste manual é custo recorrente."', 'Anônimo'),
    ('💡', '"Não existe bala de prata em engenharia de software."', 'Fred Brooks'),
    ('🔭', '"SLO breach antes de virar SLA breach: monitore o buffer."', 'Anônimo'),
    ('🌱', '"Conhecimento compartilhado é o único ativo que cresce ao ser distribuído."', 'Anônimo'),
    ('⚡', '"Core Web Vitals: Google usa UX como critério de ranking. Você usa?"', 'Anônimo'),
    ('🎵', '"Naming é a arte mais difícil da programação."', 'Phil Karlton'),
    ('🦋', '"Incremental delivery: entregue valor cedo e frequentemente."', 'Anônimo'),
    ('🌊', '"Polyglot persistence: use o banco certo para cada tipo de dado."', 'Anônimo'),
    ('🔬', '"SBOM: saiba exatamente o que está rodando no seu software."', 'Anônimo'),
    ('🏗️', '"Clean architecture: dependências apontam para dentro, nunca para fora."', 'Robert C. Martin'),
    ('🎬', '"Feature flag rollout: controle quem vê o que e quando."', 'Anônimo'),
    ('🌵', '"Disaster recovery plan não testado é plano de otimismo."', 'Anônimo'),
    ('🔮', '"Embeddings: transforme texto em geometria para que máquinas entendam semântica."', 'Anônimo'),
    ('🧬', '"Value stream mapping: visualize onde o tempo é desperdiçado no seu processo."', 'Anônimo'),
    ('🎸', '"Specification by example: exemplos concretos como documentação viva."', 'Gojko Adzic'),
    ('🏰', '"Outbox pattern: garanta que eventos sejam publicados mesmo se o sistema cair."', 'Anônimo'),
    ('🌻', '"Team topology: estruture times para otimizar fluxo de entrega."', 'Matthew Skelton'),
    ('🔴', '"MTTR baixo é mais valioso que MTBF alto."', 'Anônimo'),
    ('🎠', '"Flux/GitOps: o repositório é a fonte da verdade do cluster."', 'Anônimo'),
    ('🌴', '"Dependency inversion: dependa de abstrações, não de implementações."', 'Robert C. Martin'),
    ('🧲', '"API gateway: o porteiro inteligente dos seus microsserviços."', 'Anônimo'),
    ('🏔️', '"Latency percentiles: P99 revela a dor que a média esconde."', 'Anônimo'),
    ('🎋', '"Coupling baixo, coesão alta: a receita do bom design."', 'Larry Constantine'),
    ('🦾', '"FinOps: otimize custo cloud sem sacrificar performance."', 'Anônimo'),
    ('🌈', '"Approval testing: snapshot do comportamento esperado."', 'Anônimo'),
    ('🏊', '"Continuous learning é o único antídoto para a obsolescência técnica."', 'Anônimo'),
    ('🔵', '"Threat modeling: pense como atacante antes de construir a defesa."', 'Anônimo'),
    ('💾', '"ACID vs BASE: escolha conforme o que você não pode perder."', 'Anônimo'),
    ('🎲', '"Load testing revela o teto. Stress testing revela o ponto de ruptura."', 'Anônimo'),
    ('🌊', '"CQRS + Event Sourcing: auditoria completa de graça."', 'Anônimo'),
    ('🔩', '"Principle of least astonishment: faça o que o usuário espera."', 'Anônimo'),
    ('🌺', '"Roadmap técnico alinhado ao roadmap de produto: engenharia e produto na mesma direção."', 'Anônimo'),
    ('🎭', '"Synthetic monitoring: simule usuários reais para detectar problemas antes deles."', 'Anônimo'),
    ('🧊', '"Exponential backoff with jitter: evite thundering herd em falhas."', 'Anônimo'),
    ('🎯', '"North star metric: a única métrica que captura o valor entregue ao usuário."', 'Anônimo'),
    ('🦁', '"Staff engineer: influência técnica sem autoridade hierárquica."', 'Anônimo'),
    ('🔑', '"Secrets rotation automatizada: segurança sem depender de disciplina humana."', 'Anônimo'),
    ('🚀', '"Continuous experimentation: hipótese, teste, aprenda, repita."', 'Anônimo'),
    ('🌟', '"Engenharia de software é trabalho de equipe disfarçado de trabalho individual."', 'Anônimo'),
    ('🧠', '"Primeira lei da computação: toda abstração vaza em algum momento."', 'Joel Spolsky'),
    ('🎪', '"Sprint goal é o porquê da sprint, não o quê."', 'Anônimo'),
    ('🌍', '"Internacionalização desde o início. Retroatividade é cara."', 'Anônimo'),
    ('🏆', '"O melhor sistema de monitoramento é o que acorda o certo quando o certo falha."', 'Anônimo'),
    ('💡', '"Complexidade é o inimigo da segurança."', 'Bruce Schneier'),
    ('🔭', '"DORA metrics: frequency, lead time, MTTR, change fail rate — o pulso da engenharia."', 'DORA'),
    ('🌱', '"Contribuir para open source é aprender com os melhores de graça."', 'Anônimo'),
    ('⚡', '"Lazy loading: carregue apenas o que o usuário precisa agora."', 'Anônimo'),
    ('🎵', '"Bom software é invisível. O usuário só nota quando falta."', 'Anônimo'),
    ('🦋', '"Composability: componentes pequenos que se combinam em sistemas grandes."', 'Anônimo'),
    ('🌊', '"CAP theorem: você pode ter dois dos três. Escolha sabiamente."', 'Eric Brewer'),
    ('🔬', '"OWASP Top 10: o básico de segurança que todo desenvolvedor deve conhecer."', 'OWASP'),
    ('🏗️', '"Ports and adapters: o núcleo do sistema não conhece o mundo externo."', 'Alistair Cockburn'),
    ('🎬', '"Semantic release: versione automaticamente baseado nos commits."', 'Anônimo'),
    ('🌵', '"Recovery time objective: quanto tempo você tem para recuperar antes de impactar o negócio?"', 'Anônimo'),
    ('🔮', '"RAG: dê ao LLM o contexto que ele não tem no treinamento."', 'Anônimo'),
    ('🧬', '"Continuous architecture: arquitetura que evolui com o produto."', 'Anônimo'),
    ('🎸', '"Trunk-based development reduz conflitos de merge e aumenta integração real."', 'Anônimo'),
    ('🏰', '"Saga choreography vs orchestration: escolha o nível de controle que precisa."', 'Anônimo'),
    ('🌻', '"Cognitive load do desenvolvedor: reduza a fricção, aumente o fluxo."', 'Anônimo'),
    ('🔴', '"Error budget: quanto você pode falhar antes de parar de lançar features."', 'Google SRE'),
    ('🎠', '"Policy as code: auditoria e compliance automatizados."', 'Anônimo'),
    ('🌴', '"Coesão funcional é o mais alto nível de coesão. Busque-a."', 'Larry Constantine'),
    ('🧲', '"Developer advocacy começa com boa documentação e exemplos reais."', 'Anônimo'),
    ('🏔️', '"Partition tolerance é obrigatório em sistemas distribuídos. Escolha C ou A."', 'Eric Brewer'),
    ('🎋', '"Technical writing é habilidade de engenheiro, não de redator."', 'Anônimo'),
    ('🦾', '"Edge computing: processe onde os dados nascem, não onde você tem servidor."', 'Anônimo'),
    ('🌈', '"Accessibility não é feature extra, é requisito de inclusão."', 'Anônimo'),
    ('🏊', '"Swim against stagnation: tecnologia parada é tecnologia morrendo."', 'Anônimo'),
    ('🔵', '"Red team thinking: imagine como um atacante veria seu sistema."', 'Anônimo'),
    ('💾', '"Data quality: garbage in, garbage out — sempre foi verdade, sempre será."', 'George Fuechsel'),
    ('🎲', '"Exploratory testing sessions: boxed time para descoberta livre."', 'Anônimo'),
    ('🌊', '"Backpressure: não aceite mais do que pode processar."', 'Anônimo'),
    ('🔩', '"DRY: Don\'t Repeat Yourself, mas não ao ponto de criar acoplamento desnecessário."', 'Andy Hunt'),
    ('🌺', '"Impact mapping: conecte entregáveis a objetivos de negócio."', 'Gojko Adzic'),
    ('🎭', '"Regression test suite: o escudo contra o passado que volta para assombrar."', 'Anônimo'),
    ('🧊', '"Idempotent consumer: processe mensagens duplicadas sem efeito colateral."', 'Anônimo'),
    ('🎯', '"Exit criteria bem definidos evitam sprints que nunca terminam."', 'Anônimo'),
    ('🦁', '"Principal engineer: define o caminho técnico que outros seguem."', 'Anônimo'),
    ('🔑', '"Certificate pinning: não confie em qualquer CA, confie no que você conhece."', 'Anônimo'),
    ('🚀', '"Shift right testing: monitore o comportamento real em produção."', 'Anônimo'),
    ('🌟', '"Qualidade percebida pelo usuário é a única qualidade que importa."', 'Anônimo'),
    ('🧠', '"Dunning-Kruger em engenharia: júnior acha que sabe tudo, sênior sabe que não sabe."', 'Anônimo'),
    ('🎪', '"Scrum of scrums: sincronize times sem reuniões que escalam mal."', 'Anônimo'),
    ('🌍', '"GDPR, LGPD: privacidade por design, não por compliance reativo."', 'Anônimo'),
    ('🏆', '"Automation ROI: calcule o tempo economizado vs tempo investido. Sempre compensa."', 'Anônimo'),
    ('💡', '"Every system is perfectly designed to get the results it gets."', 'W. Edwards Deming'),
    ('🔭', '"Distributed systems time: não existe relógio global confiável."', 'Leslie Lamport'),
    ('🌱', '"Mentoring reverso: júniors ensinam sêniors sobre novas tecnologias."', 'Anônimo'),
    ('⚡', '"Time to interactive é o que o usuário sente, não o load time."', 'Anônimo'),
    ('🎵', '"Código sem testes é como música sem partitura: depende da memória de quem toca."', 'Anônimo'),
    ('🦋', '"Evolutionary database design: migre o schema junto com o código."', 'Martin Fowler'),
    ('🌊', '"Message queue: desacople produtor de consumidor no tempo e no espaço."', 'Anônimo'),
    ('🔬', '"SAST no IDE: encontre vulnerabilidades enquanto escreve, não depois."', 'Anônimo'),
    ('🏗️', '"Modular monolith: os benefícios do monolito com as fronteiras do microsserviço."', 'Anônimo'),
    ('🎬', '"Change log automatizado: o histórico que o time lê antes do release."', 'Anônimo'),
    ('🌵', '"Chaos day: quebre tudo de propósito para aprender a consertar mais rápido."', 'Anônimo'),
    ('🔮', '"Fine-tuning vs RAG: ajuste fino para comportamento, RAG para conhecimento."', 'Anônimo'),
    ('🧬', '"Site reliability engineering: a interseção entre software e operações."', 'Benjamin Treynor Sloss'),
    ('🎸', '"Commit atômico: uma mudança lógica por commit."', 'Anônimo'),
    ('🏰', '"Anti-corruption layer: proteja seu domínio de sistemas externos."', 'Eric Evans'),
    ('🌻', '"Golden path: o caminho opinionado que acelera novos times."', 'Anônimo'),
    ('🔴', '"Cascading failure: uma falha que vira várias. Isole com bulkheads."', 'Anônimo'),
    ('🎠', '"OPA: política como código, aplicada em tempo real."', 'Anônimo'),
    ('🌴', '"Acoplamento temporal: quando A precisa que B esteja disponível. Evite."', 'Anônimo'),
    ('🧲', '"Community of practice: aprenda junto, cresça junto."', 'Anônimo'),
    ('🏔️', '"PACELC: além do CAP, considere latência vs consistência."', 'Daniel Abadi'),
    ('🎋', '"Technical debt register: visibilize o que você deve antes de pagar."', 'Anônimo'),
    ('🦾', '"eBPF: observe e controle o kernel sem modificá-lo."', 'Anônimo'),
    ('🌈', '"Inclusive design: design para o extremo, melhore para todos."', 'Microsoft'),
    ('🏊', '"Swim in data: decisões baseadas em evidência, não em opinião."', 'Anônimo'),
    ('🔵', '"Defense in depth: múltiplas camadas de segurança, nunca uma só."', 'Anônimo'),
    ('💾', '"Data lineage: saiba de onde cada dado veio e para onde foi."', 'Anônimo'),
    ('🎲', '"Pairwise testing: cubra combinações críticas sem explosão combinatória."', 'Anônimo'),
    ('🌊', '"NATS, Kafka, RabbitMQ: escolha o broker certo para o padrão certo."', 'Anônimo'),
    ('🔩', '"Encapsulamento: esconda o que muda, exponha o que é estável."', 'Anônimo'),
    ('🌺', '"Continuous discovery: pesquisa de usuário não para enquanto o produto existe."', 'Teresa Torres'),
    ('🎭', '"Monitoring driven development: construa observability antes da feature."', 'Anônimo'),
    ('🧊', '"Request coalescing: agrupe requisições idênticas simultâneas em uma só."', 'Anônimo'),
    ('🎯', '"Qualidade de dados começa na coleta, não no dashboard."', 'Anônimo'),
    ('🦁', '"Distinguished engineer: impacto técnico que transcende times e produtos."', 'Anônimo'),
    ('🔑', '"Passwordless authentication: o futuro sem a fraqueza da senha."', 'Anônimo'),
    ('🚀', '"Deployment frequency alta é sinal de time maduro e processo confiável."', 'Anônimo'),
    ('🌟', '"Software que ninguém usa é o maior desperdício de engenharia."', 'Anônimo'),
    ('🧠', '"Two pizza rule: se precisa de mais que duas pizzas para alimentar o time, ele é grande demais."', 'Jeff Bezos'),
    ('🎪', '"Sprint backlog é compromisso do time, não lista de tarefas do manager."', 'Anônimo'),
    ('🌍', '"Localization é mais que tradução: é adaptação cultural."', 'Anônimo'),
    ('🏆', '"O código que você escreve hoje é o legado que alguém vai manter amanhã."', 'Anônimo'),
]


def update_readme():
    with open('README.md', 'r', encoding='utf-8') as f:
        content = f.read()

    today = datetime.utcnow()
    day_of_year = today.timetuple().tm_yday
    quote_index = (day_of_year - 1) % len(QUOTES)
    emoji, quote, author = QUOTES[quote_index]

    new_quote = f'  <!-- QUOTE_START -->\n  <i>{emoji} {quote} — {author}</i>\n  <!-- QUOTE_END -->'
    content = re.sub(
        r'  <!-- QUOTE_START -->.*?<!-- QUOTE_END -->',
        new_quote,
        content,
        flags=re.DOTALL
    )

    with open('README.md', 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Dia {day_of_year} — Frase {quote_index + 1}/{len(QUOTES)}: {emoji} {quote} — {author}")


if __name__ == '__main__':
    update_readme()
