name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

# CORREÇÃO CRÍTICA: Adiciona permissão de escrita para o GITHUB_TOKEN
# Isso permite que o bot faça o push para a branch 'output'
permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          # ATENÇÃO: Use o seu nome de usuário (Wegnernando94) se você quer suas próprias contribuições
          # Se você realmente queria o de 'rafaballerini', apenas mantenha 'rafaballerini'
          github_user_name: Wegnernando94 
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          # O token já está definido na variável de ambiente do GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
