name: Generate Datas

on:
  schedule: 
    - cron: "0 */12 * * *" 
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Wegnernando94
          svg_out_path: dist/github-contribution-grid-snake.svg
        env: 
          GITHUB_TOKEN: ${{ secrets.SNK_TOKEN }} 

      # Deploy
      - uses: crazy-max/ghaction-github-pages@v2.1.3

